spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:local
    driver-class-name: org.h2.Driver

distributed-lock:
  redisson:
    host: redis://localhost
    port: 6379